In [0]:
import torchprint(x.size())


In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

In [0]:
import torchvision

In [4]:
x=torch.rand(5,3)
print(x)

tensor([[0.3102, 0.4055, 0.1473],
        [0.5435, 0.1153, 0.2666],
        [0.4987, 0.5507, 0.8746],
        [0.9491, 0.1996, 0.2292],
        [0.5690, 0.7374, 0.3048]])


In [5]:
x=torch.empty(5,3)
print(x)

tensor([[3.9438e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1040e-05, 1.6766e+22, 2.6446e+20],
        [1.0372e-08, 6.6389e-07, 6.9001e-07],
        [1.3663e-05, 4.1911e+21, 5.0948e-14]])


In [7]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [8]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.0921, -2.6105, -1.0869],
        [ 0.6318, -2.0995,  0.7437],
        [-0.9104, -1.4822,  0.8828],
        [ 1.7516,  1.8427, -0.5536],
        [-0.1227, -0.2726, -0.1744]])


In [11]:
print(x.size())


torch.Size([5, 3])


In [14]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3577, -1.8131, -0.2822],
        [ 0.9176, -1.1122,  1.5326],
        [-0.5968, -0.8037,  1.0873],
        [ 2.2389,  2.7019,  0.3950],
        [ 0.3741,  0.5847,  0.0482]])


In [15]:
print(torch.add(x, y))


tensor([[-0.3577, -1.8131, -0.2822],
        [ 0.9176, -1.1122,  1.5326],
        [-0.5968, -0.8037,  1.0873],
        [ 2.2389,  2.7019,  0.3950],
        [ 0.3741,  0.5847,  0.0482]])


In [16]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.3577, -1.8131, -0.2822],
        [ 0.9176, -1.1122,  1.5326],
        [-0.5968, -0.8037,  1.0873],
        [ 2.2389,  2.7019,  0.3950],
        [ 0.3741,  0.5847,  0.0482]])


In [17]:
#Addition: in-place

# adds x to y
y.add_(x)
print(y)

tensor([[-0.3577, -1.8131, -0.2822],
        [ 0.9176, -1.1122,  1.5326],
        [-0.5968, -0.8037,  1.0873],
        [ 2.2389,  2.7019,  0.3950],
        [ 0.3741,  0.5847,  0.0482]])


In [18]:
print(x[:, 1])


tensor([-2.6105, -2.0995, -1.4822,  1.8427, -0.2726])


In [19]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
print(x)

tensor([[-0.1070, -1.1432,  1.9794, -0.0616],
        [-1.2197, -0.0123,  0.8420, -1.4142],
        [-0.8684,  1.2804, -1.4316, -0.7712],
        [ 0.3756, -0.4085,  0.4130,  0.4101]])


In [21]:
print(y)

tensor([-0.1070, -1.1432,  1.9794, -0.0616, -1.2197, -0.0123,  0.8420, -1.4142,
        -0.8684,  1.2804, -1.4316, -0.7712,  0.3756, -0.4085,  0.4130,  0.4101])


In [22]:
print(z)

tensor([[-0.1070, -1.1432,  1.9794, -0.0616, -1.2197, -0.0123,  0.8420, -1.4142],
        [-0.8684,  1.2804, -1.4316, -0.7712,  0.3756, -0.4085,  0.4130,  0.4101]])


In [23]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.3464])
-0.3463614583015442


In [0]:
#Numpy and Torch
#The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.



In [24]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
b = a.numpy()
print(b)


[1. 1. 1. 1. 1.]


In [26]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!